--Calculate the total revenue generated by each customer since their first order.
SELECT CustomerName, SUM(Revenue) as TotalRevenue
FROM (
    SELECT c.CustomerName, (od.Quantity * p.Price) AS Revenue
    FROM Customers c
    JOIN Orders o ON o.CustomerID = c.CustomerID
    JOIN OrderDetails od ON od.OrderID = o.OrderID
    JOIN Products p ON p.ProductID = od.ProductID
) AS RankedData
GROUP BY CustomerName
ORDER BY TotalRevenue DESC;
