--Calculate the total revenue generated by each employee for each product category
select e.FirstName, c.CategoryName, (od.Quantity*p.Price) as Revenue  
from Orders o
join Employees e on e.EmployeeID = o.EmployeeID
join OrderDetails od on od.OrderID = o.OrderID
join Products p on p.ProductID = od.ProductID
join Categories c on c.CategoryID = p.CategoryID
