--Calculate the total revenue generated by customers from each country
SELECT c.Country, sum(od.Quantity*Price) as TotalRevenue
from Customers c
join Orders o on o.CustomerID = c.CustomerID
join OrderDetails od on od.OrderID = o.OrderID
join Products p on p.ProductID = od.ProductID
group by c.Country
